### ISSUE TITLE
Bagisto does not process the PIX payment method

### ISSUE THREAD

**Issue by MarildoScopell** [Midnightgb/mercadopago-payment-gateaway#3]
Hello Julia! I hope you’re doing well. 😃😊

I’m reaching out to describe an issue I encountered. I believe the old code might have had this as well, but I hadn’t discovered it yet. It seems that Bagisto is not registering product purchases when using the “PIX” option through a web browser. I had always tested this option on my phone, where the Mercado Pago app opens with the PIX payment option — in that case, Bagisto registers the order normally. However, when using a computer with a web browser, after payment Bagisto only shows the message “Pending Payment” without registering the product order, even though Mercado Pago processes it.

Perhaps this is related to the fact that PIX is a payment method exclusive to my country, which may directly affect how the code processes it. It would be very helpful if there were a way to fix this, as it is now a common payment method here, and customers often choose it for the convenience when paying. When you have a moment, could you check if there’s a solution for this issue? I’ll be waiting. 🫡
 
<img width="300" height="366" alt="Image" src="https://github.com/user-attachments/assets/566feb38-5a71-49d1-9c71-7ce96b17c73a" /> <img width="446" height="162" alt="Image" src="https://github.com/user-attachments/assets/8c7d732f-d7a5-499b-80d2-25f13418fd4d" />

**Comment by MarildoScopell** [comment]
Hello Julian! It came very close to working. Bagisto receives the order, but if the same person makes another purchase, it doesn’t process the second order, even if it’s a different product. I tested it as if I were a customer shopping on the site. It always works for the first order, but from the second one onward it doesn’t process. I also noticed that if the order is canceled during checkout, Bagisto still marks the product status as pending and doesn’t return it to stock, even though the purchase wasn’t completed. The status doesn’t change to canceled.

**Comment by Midnightgb** [comment]
Hey Marildo! I’ve just pushed another update with fixes for both issues — multiple purchases should now work properly, and canceled/abandoned orders will return stock as expected.

Thanks a lot for your patience and for testing everything so carefully, Let me know if there’s anything else!

**Comment by MarildoScopell** [comment]
Hello Julian! Thank you for your great work. I’m very grateful for your support! I tested the new version and confirmed that it is now processing all the orders made by the customer. However, when the customer doesn’t complete the payment or clicks the button to return to the site, the order is marked as canceled, but the product still doesn’t return to the stock — it’s still necessary to do it manually. I also noticed that when the customer closes the site without performing any payment action or returning to the site, the product status remains as “pending” and it also doesn’t return to the stock. Only by canceling it manually.

<img width="536" height="260" alt="Image" src="https://github.com/user-attachments/assets/4a7c75bf-a598-473c-8077-b51adb6197d8" />

<img width="506" height="157" alt="Image" src="https://github.com/user-attachments/assets/d0a43219-2549-4023-87ec-927aba8c1af1" />

**Comment by Midnightgb** [comment]
Hi marildo, thank you so much for testing again and for the detailed feedback 

I’ve just updated the integration so that now when Mercado Pago reports an order as expired (after the payment window closes), it will be automatically cancelled and the stock will be restored  the same as when it’s cancelled or rejected.

Could you please help me test this scenario again?

Start a new order and go to the payment page.

Don’t complete the payment and wait until the payment link expires (currently set to 1h).

Once Mercado Pago sends the expired status, the system should cancel the order and return the stock automatically.

This will cover the case when a customer simply leaves the site without paying.
Let me know the results and if everything works as expected!

**Comment by MarildoScopell** [comment]
Hi Julian! Sorry for the delay in testing this new version—I noticed that the apparent issues have indeed been resolved. One thing we observed is that when the user clicks the “Place Order” button multiple times, the order ends up being duplicated in the Bagisto admin panel. Regarding IPN, do you plan to switch to webhooks? I saw that IPNs may possibly be discontinued by Mercado Pago. Besides that, thank you for your help!

**Comment by Midnightgb** [comment]
Hey Marildo! Thanks again for testing and sharing your observations 🙌

About the duplicate orders: this actually comes from Bagisto’s core, not from the Mercado Pago integration. When the “Place Order” button is clicked multiple times, Bagisto processes each click and creates multiple orders with the same cart. It’s a limitation in Bagisto itself. If this behavior is an issue for your store, I’d recommend reporting it directly to the Bagisto team so they can handle it at the core level.

Regarding IPN: yes, Mercado Pago is moving everything to “webhooks”. Functionally they work the same, but I’ll update the integration later to follow the new naming and make sure it stays future-proof.

Thanks again for all your feedback — it really helps improve the extension

**Comment by MarildoScopell** [comment]
great job!
